### ISSUE TITLE
삭제된 게시물에 대한 좋아요 알림을 AlarmStoreView에서 클릭하는 경우 404 Error 페이지 대신 ‘삭제된 게시글입니다.’ 띄워주기

### ISSUE THREAD

**Issue by Phangg** [APP-iOS3rd/PJ3T7_HrMi#181]
현재 NavigationStack 의 Destination 에서, Route 에 제대로 접근하지 못하는 경우에 ErrorView 를 보여주고 있습니다.

이때, 제대로 접근하지 못하는 경우는 Route 에 없는 case 혹은 제대로된 프로퍼티를 갖고 접근하지 못하는 경우입니다.
→ switch 문의 default case 에 해당하는 경우입니다.

삭제 된 게시물 ( 본인의 게시물 or 상대의 게시물 ) & 삭제된 프로필 의 경우에 접근을 하지 못할 것으로 예상이 되는데요,
이때, 다른 무언가의 장치를 해서 다른 페이지에 가게 하는 방법을 쓰는게 맞다고 생각했기에.. ErrorView 를 건드는 것으로는 해결하는것이 어울리지 않는것 같다는 생각이 들었습니다.

그렇다면 어떻게 하는 것이 좋을까..?

음.. 다른 페이지를 새로 구성하거나 보여주는 뷰를 변경하는 과정을 하는 것도 좋지만,
ErrorView 에 접근 하는 경우를 먼저 생각해봤습니다.

프로필, 게시물이 삭제되는 경우 외에는 ErrorView 에 접근하는 일이 없을 것 같습니다..
그래서 제가 생각한 부분은.. ErrorView 에서 `잘못된 페이지 요청입니다. 🥲 🍸` 라는 텍스트를 유지하면서, 
추가적인 텍스트로 `삭제되었거나 현재 존재하지 않는 데이터입니다.` 라고 주는것은 어떨까 생각했습니다.

그리고, 상단 Toolbar 에 Principal 로 들어간 `🍺 404 Not Found 🍺`  텍스트는 없는게 나을 것 같아요!

@bdrsky2010 @withseon 
의견 남겨주시면 좋을 것 같아요..!

**Comment by withseon** [comment]
좋은 생각 같아요!
앱 테스팅하면서, AlarmStoreView에서 삭제된 게시글에 접근했을 때 나오는 뷰의 타이틀이나 내용이 어색하기도 하고
이렇게 되면 해당 정보가 없어서 접근을 못하는지, 앱의 동작 과정 중 문제가 나서 접근을 못하는지 분별이 어려울 거 같다는 생각을 했습니다!
말씀하신 방식대로 구체적 내용을 명시한다면, 이런 혼란을 없앨 수 있을 거 같습니다 - ! 😄

**Comment by bdrsky2010** [comment]
동의합니다
